'use strict';
const KEY='fabrogym_mvp_final_v1';
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const addDays=(n)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const uid=(p)=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2,6)}`;
const users={admin:{password:'admin123',role:'Administrador'},recepcion:{password:'recep123',role:'Recepción'},instructor:{password:'instr123',role:'Instructor'}};
const seed={clients:[
{id:'CLI-S01',doc:'0999999901',name:'Andrea Torres',phone:'0990000001',status:'Activo',plan:'Mensual',expiry:addDays(2)},
{id:'CLI-S02',doc:'0999999902',name:'Carlos Mendoza',phone:'0990000002',status:'Activo',plan:'Trimestral',expiry:addDays(24)},
{id:'CLI-S03',doc:'0999999903',name:'Daniela Ruiz',phone:'0990000003',status:'Inactivo',plan:'Mensual',expiry:addDays(-5)},
{id:'CLI-S04',doc:'0999999904',name:'Javier León',phone:'0990000004',status:'Activo',plan:'Mensual',expiry:addDays(6)}],
attendance:[{id:'ASI-S01',clientId:'CLI-S02',date:today(),time:'07:15',shift:'Mañana',channel:'Recepción'},{id:'ASI-S02',clientId:'CLI-S04',date:today(),time:'16:10',shift:'Tarde',channel:'Código QR simulado'}],
routines:[{id:'RUT-S01',clientId:'CLI-S01',instructor:'Instructor Alfa',name:'Adaptación general',exercise:'Prensa guiada',sets:'3 × 12',rest:'60 segundos',status:'Activa',version:1,followups:[]}]};
let state=load();let session=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(error){console.warn('Persistencia local no disponible en esta vista de demostración.')}}
function client(id){return state.clients.find(c=>c.id===id)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={dashboard:'Resumen operativo',clients:'Clientes y membresías',attendance:'Gestión de asistencias',routines:'Gestión de rutinas',coverage:'Cobertura del MVP'};$('#pageTitle').textContent=titles[id]||'FabroGym';renderAll()}
function login(user){session={user,role:users[user].role};$('#currentUser').textContent=user;$('#currentRole').textContent=session.role;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');applyRole();renderAll();toast(`Sesión iniciada como ${session.role}`)}
function applyRole(){const isInstructor=session.role==='Instructor';$$('[data-view="clients"]').forEach(x=>x.style.display=isInstructor?'none':'flex');if(isInstructor)navigate('routines')}
function statusFor(c){const expired=c.expiry<today();if(c.status!=='Activo'||expired)return 'No vigente';return 'Vigente'}
function renderAll(){fillSelects();renderDashboard();renderClients();renderAttendance();renderRoutines();renderCoverage()}
function fillSelects(){const active=state.clients.filter(c=>c.status==='Activo');for(const id of ['attendanceClient','routineClient']){const el=$(`#${id}`);const old=el.value;el.innerHTML=active.map(c=>`<option value="${c.id}">${c.name} — ${c.doc}</option>`).join('');if(active.some(c=>c.id===old))el.value=old}}
function renderDashboard(){const active=state.clients.filter(c=>c.status==='Activo');$('#statClients').textContent=active.length;$('#statMemberships').textContent=active.filter(c=>statusFor(c)==='Vigente').length;$('#statAttendance').textContent=state.attendance.filter(a=>a.date===today()).length;$('#statRoutines').textContent=state.routines.filter(r=>r.status==='Activa').length;const exp=[...state.clients].sort((a,b)=>a.expiry.localeCompare(b.expiry)).slice(0,4);$('#expiryList').innerHTML=exp.map(c=>{const days=Math.ceil((new Date(c.expiry)-new Date(today()))/86400000);const cls=days<0?'off':days<=7?'warn':'ok';const txt=days<0?'Vencida':`${days} día(s)`;return `<div class="list-item"><div><b>${c.name}</b><small>${c.plan} · vence ${c.expiry}</small></div><span class="badge ${cls}">${txt}</span></div>`}).join('');const recent=[...state.attendance].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).slice(0,4);$('#recentList').innerHTML=recent.map(a=>`<div class="list-item"><div><b>${client(a.clientId)?.name||'Cliente'}</b><small>${a.shift} · ${a.channel}</small></div><span class="badge ok">${a.time}</span></div>`).join('')}
function renderClients(){const q=$('#clientSearch').value.toLowerCase();const rows=state.clients.filter(c=>`${c.name} ${c.doc}`.toLowerCase().includes(q));$('#clientTable').innerHTML=rows.map(c=>`<tr><td><b>${c.name}</b><br><small>${c.doc}</small></td><td>${c.plan}</td><td>${c.expiry}</td><td><span class="badge ${statusFor(c)==='Vigente'?'ok':'off'}">${statusFor(c)}</span></td><td><div class="row-actions"><button class="mini" data-edit="${c.id}">Editar</button><button class="mini" data-renew="${c.id}">Renovar</button></div></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editClient(b.dataset.edit));$$('[data-renew]').forEach(b=>b.onclick=()=>renewClient(b.dataset.renew))}
function editClient(id){const c=client(id);$('#clientEditId').value=id;$('#clientDoc').value=c.doc;$('#clientName').value=c.name;$('#clientPhone').value=c.phone;$('#clientStatus').value=c.status;$('#clientPlan').value=c.plan;$('#clientExpiry').value=c.expiry;window.scrollTo({top:0,behavior:'smooth'})}
function renewClient(id){const c=client(id);const d=new Date(Math.max(new Date(c.expiry),new Date()));d.setDate(d.getDate()+(c.plan==='Trimestral'?90:c.plan==='Pase diario'?1:30));c.expiry=d.toISOString().slice(0,10);c.status='Activo';save();renderAll();toast(`Membresía renovada hasta ${c.expiry}`)}
function renderAttendance(){const q=$('#attendanceSearch').value.toLowerCase(),date=$('#attendanceFilterDate').value;const rows=state.attendance.filter(a=>(!q||(client(a.clientId)?.name||'').toLowerCase().includes(q))&&(!date||a.date===date)).sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`));$('#attendanceTable').innerHTML=rows.map(a=>`<tr><td><b>${client(a.clientId)?.name||'Cliente'}</b></td><td>${a.date}</td><td>${a.time}</td><td>${a.shift}</td><td>${a.channel}</td></tr>`).join('')||'<tr><td colspan="5">Sin registros.</td></tr>'}
function renderRoutines(){const rows=state.routines;$('#routineCards').innerHTML=rows.map(r=>`<article class="routine-card"><div class="routine-top"><div><h4>${r.name}</h4><div class="muted">${client(r.clientId)?.name||'Cliente'} · ${r.instructor} · versión ${r.version}</div></div><span class="badge ${r.status==='Activa'?'ok':'off'}">${r.status}</span></div><div class="routine-meta"><span><b>Ejercicio</b><br>${r.exercise}</span><span><b>Series</b><br>${r.sets}</span><span><b>Descanso</b><br>${r.rest}</span></div><button class="btn secondary" data-follow="${r.id}">Registrar seguimiento</button><div class="followups"><b>Seguimientos (${r.followups.length})</b>${r.followups.length?`<ul>${r.followups.slice().reverse().map(f=>`<li>${f.date}: ${f.compliance}${f.note?` — ${f.note}`:''}</li>`).join('')}</ul>`:'<div class="muted">Sin seguimientos registrados.</div>'}</div></article>`).join('');$$('[data-follow]').forEach(b=>b.onclick=()=>openFollowup(b.dataset.follow))}
const coverage=[['RF-AUT-01','Autenticar usuario'],['RF-AUT-02','Aplicar permisos por rol'],['RF-CLI-01','Registrar cliente mínimo'],['RF-CLI-02','Buscar y consultar cliente'],['RF-CLI-03','Actualizar/reactivar cliente'],['RF-MEM-02','Activar o renovar membresía'],['RF-MEM-03','Consultar vigencia'],['RF-MEM-04','Alertar vencimientos'],['RF-ASI-01','Registrar asistencia'],['RF-ASI-02','Consultar asistencia'],['RF-RUT-01','Administrar rutinas'],['RF-RUT-02','Registrar seguimiento']];
function renderCoverage(){$('#coverageGrid').innerHTML=coverage.map(([id,d])=>`<div class="coverage-item"><b>${id}</b><span>${d}</span><span class="badge ok">Implementado</span></div>`).join('')}
function openFollowup(id){$('#followupRoutineId').value=id;$('#followupDate').value=today();$('#followupCompliance').value='Completa';$('#followupNote').value='';$('#followupDialog').showModal()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(users[u]?.password===p)login(u);else toast('Credenciales incorrectas')});
$('#logoutBtn').onclick=()=>{session=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')};
$$('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.jump));
$('#clientForm').addEventListener('submit',e=>{e.preventDefault();const edit=$('#clientEditId').value,doc=$('#clientDoc').value.trim();const duplicate=state.clients.find(c=>c.doc===doc&&c.id!==edit);if(duplicate){toast('No se permite duplicar la identificación');return}const data={doc,name:$('#clientName').value.trim(),phone:$('#clientPhone').value.trim(),status:$('#clientStatus').value,plan:$('#clientPlan').value,expiry:$('#clientExpiry').value};if(edit)Object.assign(client(edit),data);else state.clients.push({id:uid('CLI'),...data});save();clearClient();renderAll();toast(edit?'Cliente actualizado':'Cliente registrado')});
function clearClient(){$('#clientForm').reset();$('#clientEditId').value='';$('#clientStatus').value='Activo';$('#clientPlan').value='Mensual';$('#clientExpiry').value=addDays(30)}$('#clearClient').onclick=clearClient;$('#clientSearch').oninput=renderClients;
$('#attendanceForm').addEventListener('submit',e=>{e.preventDefault();const c=client($('#attendanceClient').value),date=$('#attendanceDate').value;const result=$('#attendanceResult');result.classList.remove('hidden','error');if(!c||statusFor(c)!=='Vigente'){result.textContent='Ingreso rechazado: la membresía no está vigente.';result.classList.add('error');return}if(state.attendance.some(a=>a.clientId===c.id&&a.date===date)){result.textContent='Registro duplicado: el cliente ya tiene asistencia en esta fecha.';result.classList.add('error');return}state.attendance.push({id:uid('ASI'),clientId:c.id,date,time:$('#attendanceTime').value,shift:$('#attendanceShift').value,channel:$('#attendanceChannel').value});save();result.textContent=`Ingreso confirmado para ${c.name}.`;renderAll();toast('Asistencia registrada correctamente')});
$('#attendanceSearch').oninput=renderAttendance;$('#attendanceFilterDate').onchange=renderAttendance;$('#exportAttendance').onclick=()=>download('asistencias_fabrogym.csv','cliente,fecha,hora,turno,canal\n'+state.attendance.map(a=>`${client(a.clientId)?.name},${a.date},${a.time},${a.shift},${a.channel}`).join('\n'),'text/csv');
$('#routineForm').addEventListener('submit',e=>{e.preventDefault();state.routines.push({id:uid('RUT'),clientId:$('#routineClient').value,instructor:$('#routineInstructor').value,name:$('#routineName').value.trim(),exercise:$('#routineExercise').value.trim(),sets:$('#routineSets').value.trim(),rest:$('#routineRest').value.trim(),status:$('#routineStatus').value,version:1,followups:[]});save();e.target.reset();renderAll();toast('Rutina creada y asignada')});
$('#followupForm').addEventListener('submit',e=>{e.preventDefault();const r=state.routines.find(x=>x.id===$('#followupRoutineId').value);r.followups.push({date:$('#followupDate').value,compliance:$('#followupCompliance').value,note:$('#followupNote').value.trim()});save();$('#followupDialog').close();renderAll();toast('Seguimiento registrado')});$('#closeDialog').onclick=()=>$('#followupDialog').close();
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Archivo exportado')}
$('#attendanceDate').value=today();$('#attendanceTime').value=nowTime();$('#clientExpiry').value=addDays(30);$('#followupDate').value=today();
